### PR TITLE
Handele exceptions more graceful.

### PR DESCRIPTION
**Pull request by jaap3**
Here's some things I fixed after setting up nudge for the first time and having some configuration issues.

This handles a few cases more gracefully:
- wrapping send_command in a try catch, this makes a misconfigured endpoints a bit easier to identify.
- push_one now catches the exception raised by send_command, so pushing to a misconfigured endpoint actually marks the batch as failed.
- process_batch had mixed tabs and spaces, checked a magic number and did a weird type check. Hopefully cleaned that up correctly.
- Handle a misconfigured NUDGE_SELECTIVE setting a bit more graceful, by catching ContentType.DoesNotExist and making sure all lookup values are lowercased.

Also cleans up the code of the methods I touched a bit. There were mixed tabs and spaces for example, could do a pep8 cleanup of the entire codebase if that's appreciated.

### CODE REVIEW

**Comment by rosskarchner** [comment]
Thanks, we'll review this and most likely merge.

Any PEP8 improvements would CERTAINLY be appreciated, too!

**Comment by jaap3** [comment]
Created a PEP8 pull request. Think it would be easier to merge that one first, so I can fix this one to apply cleanly.

**Comment by rosskarchner** [comment]
Your PEP8 branch has been pulled in-- let me know when you consider this ready.

**Comment by rosskarchner** [comment]
I've incorporated these changes into a new pull request (#53) that resolves the resulting conflicts, so I'm going to close this one.

**Pull request closed without merging**
